#!/usr/bin/env bash
LS_ERROR="GVM couldn't find ls"
GREP_ERROR="GVM couldn't find grep"
SORT_ERROR="GVM couldn't find sort"
HEAD_ERROR="GVM couldn't find head"

LS_PATH=$(unalias ls &> /dev/null; command -v ls) || __gvm_display_error "$LS_ERROR" || return 1
GREP_PATH=$(unalias grep &> /dev/null; command -v grep) || __gvm_display_error "$GREP_ERROR" || return 1
SORT_PATH=$(unalias sort &> /dev/null; command -v sort) || __gvm_display_error "$SORT_ERROR" || return 1
HEAD_PATH=$(unalias head &> /dev/null; command -v head) || __gvm_display_error "$HEAD_ERROR" || return 1

