#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

[[ $1 != "" ]] ||
	__gvm_display_fatal "Please specify the alias name"

[[ $2 != "" ]] ||
	__gvm_display_fatal "Please specify the go version name"

[[ ! -f "$GVM_ROOT/environments/$1" ]] ||
	__gvm_display_fatal "Alias already exists!"
[[ -f "$GVM_ROOT/environments/$2" ]] ||
	__gvm_display_fatal "Target doesn't exist!"

mkdir -p "$GVM_ROOT/environments" ||
	__gvm_display_fatal "Could not create folder"
mkdir -p "$GVM_ROOT/gos/$1" ||
	__gvm_display_fatal "Could not create folder"
cp "$GVM_ROOT/environments/$2" "$GVM_ROOT/environments/$1" ||
	__gvm_display_fatal "Could copy environment"
echo "export gvm_alias_name=\"$1\"" >> "$GVM_ROOT/environments/$1" ||
	__gvm_display_fatal "Could not extend environment"

