#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

[[ $1 != "" ]] ||
	__gvm_display_fatal "Please specify the name"

[[ -f $GVM_ROOT/environments/$1 ]] ||
	__gvm_display_fatal "Alias doesn't exist!"

\grep "gvm_alias_name" "$GVM_ROOT/environments/$1" > /dev/null ||
	__gvm_display_fatal "$1 is not an alias!"

rm -rf "$GVM_ROOT/environments/$1" ||
	__gvm_display_fatal "Could not delete alias"

rm -rf "$GVM_ROOT/gos/$1" ||
	__gvm_display_fatal "Could not delete alias"

