#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

version=$1

if [ "$version" != "" ]; then
  fuzzy_match=$(\ls -1 "$GVM_ROOT/gos" | \sort | \grep "$version" | $HEAD_PATH -n 1 | \grep "$version") ||
		__gvm_display_fatal "Invalid version $version"

	foldername=$GVM_ROOT/gos/$fuzzy_match
else
	if [[ "$gvm_go_name" != "" ]]; then
		foldername=$GVM_ROOT/gos/$gvm_go_name
	else
		__gvm_display_fatal "No version selected"
	fi
fi

if [[ -d $foldername ]]; then
	builtin cd "$foldername"
	find . > /tmp/manifest.test
	diff manifest /tmp/manifest.test
	if [[ "$?" == "0" ]]; then
		__gvm_display_message "Clean $foldername"
	else
		__gvm_display_message "*Dirty* $foldername"
	fi
else
	__gvm_display_fatal "Invalid version"
fi
