#!/usr/bin/env bash
source "$GVM_ROOT/scripts/functions"

[[ -d $GVM_ROOT/.git ]] || mv "$GVM_ROOT/git.bak" "$GVM_ROOT/.git" &> /dev/null ||
	__gvm_display_fatal "Couldn't find git info"

builtin cd "$GVM_ROOT"

if [[ -n $1 ]]; then
  git checkout "$1" -f || __gvm_display_fatal "Failed to checkout $1 branch"
else
  git checkout -f || __gvm_display_fatal "Failed to clean install"
fi

git pull || __gvm_display_fatal "Failed to update"

mv ".git" "git.bak" || __gvm_display_fatal "Couldn't backup git info"
