#!/usr/bin/env bash
. "$GVM_ROOT/scripts/functions"

error_message=""

# Check for git
command -v git &> /dev/null ||
	error_message="${error_message}
Could not find git

  linux: apt-get install mercurial
  mac:   brew install mercurial
"
# Check for ar
command -v ar &> /dev/null ||
	error_message="${error_message}
Could not find binutils

  linux: apt-get install binutils
"
# Check for bison
command -v bison &> /dev/null ||
	error_message="${error_message}
Could not find bison

  linux: apt-get install bison
"
# Check for gcc
command -v gcc &> /dev/null ||
	error_message="${error_message}
Could not find gcc

  linux: apt-get install gcc
"
# Check for make
command -v make &> /dev/null ||
	error_message="${error_message}
Could not find make

  linux: apt-get install make
"
# Check for curl
command -v curl &> /dev/null ||
	error_message="${error_message}
Could not find curl

  linux: apt-get install curl
  mac:   brew install curl
"

# Check for hexdump (for bash_pseudo_hash)
command -v hexdump &> /dev/null ||
    error_message="${error_message}
Could not find hexdump
  linux: apt-get install bsdmainutils
"

if [ -n "$error_message" ]; then
	__gvm_display_warning "$error_message"
	exit 1
else
	# All good!
	exit 0
fi
