#!/usr/bin/env bash
source "$GVM_ROOT/scripts/functions"

[[ $gvm_pkgset_name != "" ]] ||
	__gvm_display_fatal "No Package set selected"
rm -rf "$GVM_ROOT/pkgsets/$gvm_go_name/$gvm_pkgset_name/"* ||
	__gvm_display_fatal "Could not delete package set files"

