#!/usr/bin/env bash
# scripts/pkgset
#
# shellcheck shell=bash
# vi: set ft=bash
#

# load dependencies
dep_load()
{
    local base="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && builtin pwd)"
    local deps; deps=(
        "../scripts/function/_shell_compat.sh"
        "../scripts/function/locale_text.sh"
        "../scripts/env/pkgset_use.sh"
    )
    for file in "${deps[@]}"
    do
        source "${base}/${file}"
    done
}; dep_load; unset -f dep_load

_exit()
{
  stty sane; echo; __gvm_display_fatal "caught signal, shutting down"

  # @TODO: additional cleanup?

  wait; stty sane; exit 1
}

trap '_exit' SIGINT SIGQUIT SIGTERM

main()
{
    local rslt

    if [[ -n "$GVM_DEBUG" ]] && [[ -n "$GVM_DEBUG_LEVEL" && "$GVM_DEBUG_LEVEL" -gt 1 ]]
    then
        set -x
    fi

    while true
    do
        case "${1}" in
            create | delete | empty | list )
                local command="${1}"
                shift
                "${GVM_ROOT}/scripts/pkgset-${command}" "$@"
                rslt=$?; unset command; break
                ;;
            use )
                shift
                __gvm_pkgset_use "$@"
                rslt=0; break
                ;;
            -h | ? | help | --help )
                __gvm_locale_text_for_key "help/usage_pkgset" > /dev/null
                printf "%s\n" "${RETVAL}"
                rslt=0; break
                ;;
            *)
                __gvm_locale_text_for_key "unrecognized_command" > /dev/null
                printf "%s: %s\n\n" "${RETVAL}" "${1:-empty}"
                __gvm_locale_text_for_key "help/usage_pkgset" > /dev/null
                printf "%s\n" "${RETVAL}"
                rslt=1; break
                ;;
        esac
        # guard against accidents...
        shift; [[ "$#" -eq 0 ]] && break
    done

    if [[ -n "$GVM_DEBUG" ]] && [[ -n "$GVM_DEBUG_LEVEL" && "$GVM_DEBUG_LEVEL" -gt 1 ]]
    then
        set +x
    fi

    return "${rslt}"
}

main "$@"
