#!/usr/bin/env bash
source "$GVM_ROOT/scripts/function/_load_common.sh"

[[ "$1" == "" ]] &&
	__gvm_display_fatal "Please specify the version"

fuzzy_match=$(\ls -1 "$GVM_ROOT/gos" | \sort | \grep "$1" | \head -n 1 | \grep "$1") ||
	__gvm_display_fatal "Invalid version $1"

if [[ -d $GVM_ROOT/gos/$fuzzy_match ]]; then
	rm -rf "$GVM_ROOT/pkgsets/$fuzzy_match" &> /dev/null ||
		__gvm_display_fatal "Couldn't remove pkgsets"
	rm -f "$GVM_ROOT/environments/$fuzzy_match" &> /dev/null ||
		__gvm_display_fatal "Couldn't remove environment files"
	rm -f "$GVM_ROOT/environments/$fuzzy_match@"* &> /dev/null ||
		__gvm_display_fatal "Couldn't remove pkgset environment files"
	rm -rf "$GVM_ROOT/gos/$fuzzy_match" &> /dev/null ||
		__gvm_display_fatal "Couldn't remove Go folder"
	__gvm_display_message "Uninstalled version $fuzzy_match"
else
	__gvm_display_fatal "Invalid version"
fi
