#!/usr/bin/env bash
source "$GVM_ROOT/scripts/functions"

builtin cd "$GVM_ROOT/archive/go" &> /dev/null ||
	__gvm_display_fatal "Failed to find local Go source"

git pull || __gvm_display_fatal "Failed to update"
